### ISSUE TITLE
[BUG| Unexpected Theme Change in Light Mode

### ISSUE THREAD

**Issue by roy7077** [Vasu7389/react-project-ideas#20]
### Description
When refreshing the site or clicking on "React" in the menu while in light mode, the theme initially appears as black before changing to the light theme. This behavior is unexpected and may confuse users.

### Steps to Reproduce
1. Open the site in light mode.
2. Refresh the page.
3. Observe that the theme briefly appears as black before changing to the light theme.
4. Click on "React" in the menu.
5. Observe the same behavior: the theme briefly appears as black before changing to the light theme.

### Expected Behavior
The theme should remain consistent in light mode without momentarily changing to the black theme when refreshing the page or navigating through the menu.

### Additional Information
- Operating System: [Window]
- Browser: [Chrome, Edge]
- Video:

https://github.com/Vasu7389/react-project-ideas/assets/107414907/9943043c-595a-4201-afbc-efefaadd2116

**Comment by Vasu7389** [comment]
Thanks for reporting.
