### ISSUE TITLE
Update license section in README

### ISSUE THREAD

**Issue by freedompraise** [Vasu7389/react-project-ideas#4]
The README could have a license section that clarifies the terms and conditions of using the project. It could inform users of their rights and obligations when using or modifying the project.

**Comment by Vasu7389** [comment]
Do you want me to make changes in the license file?
Because currently it already has "MIT License".

**Comment by ahmedjanwar** [comment]
probably you can update it as : 

## License
[MIT](https://choosealicense.com/licenses/mit/)
