### ISSUE TITLE
Update contribution section in README

### ISSUE THREAD

**Issue by freedompraise** [Vasu7389/react-project-ideas#5]
The contribution section should link to the contributors file for easy documentation flow

**Comment by Vasu7389** [comment]
Could you give any example?

**Comment by Hardik-369** [comment]
> Could you give any example?

Step 1: Create a Contributors File
In your project repository, create a file named CONTRIBUTORS.md or any other appropriate name.

Add the list of contributors with their names, GitHub usernames, and any other relevant information.

Example CONTRIBUTORS.md:

markdown
Copy code
# Contributors

- John Doe (@johndoe)
- Jane Smith (@janesmith)
Step 2: Update Contribution Guidelines
If you don't have a CONTRIBUTING.md file, create one in the root of your repository.

Open or create CONTRIBUTING.md and add a section that includes a link to the CONTRIBUTORS.md file.

Example CONTRIBUTING.md:

markdown
Copy code
# Contributing to [Your Project Name]

Thank you for considering contributing to [Your Project Name]! ...

## How to Contribute

...

### Acknowledgements

We would like to thank the following contributors:

- [List of Contributors](CONTRIBUTORS.md)

Step 3: Commit and Push Changes
Save your changes to both CONTRIBUTORS.md and CONTRIBUTING.md.

Commit your changes and push them to your GitHub repository.

bash
Copy code
git add CONTRIBUTORS.md CONTRIBUTING.md
git commit -m "Add contributors file and update contribution guidelines"
git push origin main
Step 4: Verify Links on GitHub
Go to your GitHub repository on the web.
Open the CONTRIBUTING.md file.
Verify that the link to the CONTRIBUTORS.md file is working correctly.

**Comment by JaneSmith** [comment]
Why was I tagged here?

**Comment by JaneSmith** [comment]
Please don't @ tag random people that have nothing to do with your project. :(
